# Maintainer: Pete Jackson <pete@tern.travel>
pkgname=omarchy-zfs
pkgver=1.2.0
pkgrel=1
pkgdesc="Root-on-ZFS + ZFSBootMenu support layer for Omarchy (Quattro)"
arch=('any')
url="https://github.com/peteonrails/omarchy-zfs"
license=('MIT')
# Hard-dep omarchy (decision 7.1): one-command install of the full Quattro
# stack plus the ZFS layer. omarchy-dev provides/conflicts omarchy, so this is
# satisfied on any channel. Inert limine/snapper pulled in transitively are
# masked/ignored by the .install.
#
# ZFS deps use the VIRTUAL provides (`zfs`, `zfs-utils`) rather than a concrete
# package, so any provider satisfies them: zfs-dkms / zfs-dkms-git (DKMS,
# kernel-strategy A) OR the prebuilt zfs-linux / zfs-linux-lts. This avoids
# breaking existing installs and lets the kernel strategy be chosen at install
# time (see omarchy-zfs-kernel-install + the kernel guard).
depends=(
  'omarchy'
  'zfs'          # kernel module — any provider (zfs-dkms, zfs-dkms-git, zfs-linux, zfs-linux-lts)
  'zfs-utils'    # userspace + the /usr/lib/initcpio zfs hook — any provider
  'libunwind'    # zfs-utils(-git) links libunwind.so.8 but doesn't declare it;
                 # without it mkinitcpio silently omits zpool/mount.zfs -> unbootable initramfs
  'sanoid'
  'efibootmgr'
)
optdepends=(
  # zfsbootmenu is AUR/manual (no binary repo), and ZBM is frequently installed
  # from prebuilt EFI images rather than the package -- so it CANNOT be a hard
  # dep (pacman -S omarchy-zfs would fail to resolve it). Install ZBM yourself.
  'zfsbootmenu: ZFSBootMenu boot manager (AUR or prebuilt EFI images)'
  'lzop: faster syncoid stream compression'
  'mbuffer: syncoid network buffering'
  'pv: syncoid transfer progress'
  # Remote unlock: only needed on headless/remote boxes, and only with a
  # locally generated ZBM image. omarchy-zfs-remote-unlock-setup offers to
  # install these when it needs them.
  'dropbear: SSH access to the ZFSBootMenu prompt (omarchy-zfs-remote-unlock-setup)'
  'mkinitcpio-nfs-utils: DHCP networking inside the ZBM image (remote unlock, --dhcp)'
  'curl: fetch the pool key from a keyserver (omarchy-zfs-netkey-setup)'
  'binutils: verify the contents of the generated ZBM EFI image'
)
# autosnap.conf is admin-editable; never clobber it on upgrade.
backup=('etc/omarchy-zfs/autosnap.conf' 'etc/omarchy-zfs/bootorder.conf')
install="${pkgname}.install"
# Local dev builds fetch nothing (payload lives alongside the PKGBUILD).
# The published AUR PKGBUILD is this same file with the release tarball as
# source — generated by aur/release.sh, never edited by hand.
source=()

package() {
  # AUR build: payload extracted from the release tarball. Dev build: $startdir.
  local S="$srcdir/$pkgname-$pkgver"
  [[ -d $S ]] || S="$startdir"

  # --- CLI tools -> /usr/bin ---
  local bins=(
    omarchy-fs-type omarchy-fs-zfs omarchy-fs-btrfs
    omarchy-cmdline-add omarchy-refresh-zbm
    omarchy-zfs-snapshot omarchy-zfs-scrub omarchy-zfs-kernel-compat-check
    omarchy-zfs-autosnap omarchy-zfs-ensure-mkinitcpio omarchy-zfs-kernel-install
    omarchy-zfs-snapper-guard omarchy-zfs-bootorder-guard
    omarchy-zfs-hibernation-setup omarchy-zfs-hibernation-remove omarchy-zfs-hibernation-available
    omarchy-zfs-remote-unlock-setup omarchy-zfs-remote-unlock-remove
    omarchy-zfs-netkey-setup omarchy-zfs-netkey-remove
    omarchy-bootstrap-zfs
  )
  local b
  for b in "${bins[@]}"; do
    install -Dm755 "$S/bin/$b" "$pkgdir/usr/bin/$b"
  done

  # --- pacman/libalpm hooks -> /usr/share/libalpm/hooks ---
  local hooks=(
    00-zfs-autosnap.hook
    90-omarchy-zfs-kernel-guard.hook
    zz-omarchy-zfs-ensure-mkinitcpio.hook
    zz-omarchy-zfs-snapper-guard.hook
    zz-omarchy-zfs-bootorder-guard.hook
  )
  local h
  for h in "${hooks[@]}"; do
    install -Dm644 "$S/hooks/$h" "$pkgdir/usr/share/libalpm/hooks/$h"
  done

  # --- systemd units -> /usr/lib/systemd/system ---
  # Make journald wait for the /var/log dataset, or the system logs nowhere.
  install -Dm644 "$S/systemd/systemd-journal-flush.service.d/zfs-var-log.conf" \
    "$pkgdir/usr/lib/systemd/system/systemd-journal-flush.service.d/zfs-var-log.conf"

  install -Dm644 "$S/systemd/omarchy-zfs-scrub.service" "$pkgdir/usr/lib/systemd/system/omarchy-zfs-scrub.service"
  install -Dm644 "$S/systemd/omarchy-zfs-scrub.timer"   "$pkgdir/usr/lib/systemd/system/omarchy-zfs-scrub.timer"

  # --- shared shell library -> /usr/share/omarchy-zfs/lib ---
  install -Dm644 "$S/lib/remote-unlock.sh" "$pkgdir/usr/share/omarchy-zfs/lib/remote-unlock.sh"

  # --- ZFSBootMenu config reference + hooks -> /etc/zfsbootmenu ---
  install -Dm644 "$S/zfsbootmenu/config.yaml.example" "$pkgdir/etc/zfsbootmenu/config.yaml.example"
  install -Dm755 "$S/zfsbootmenu/hooks/load-key.d/01-omarchy-unlock.sh" "$pkgdir/etc/zfsbootmenu/hooks/load-key.d/01-omarchy-unlock.sh"
  install -Dm755 "$S/zfsbootmenu/hooks/setup.d/01-omarchy-theme.sh"     "$pkgdir/etc/zfsbootmenu/hooks/setup.d/01-omarchy-theme.sh"

  # Network key fetch. Always installed, inert until omarchy-zfs-netkey-setup
  # writes /etc/omarchy-netkey.conf -- the hook exits immediately without it, so
  # baking it into every ZBM image costs nothing and makes enabling a config-only
  # change.
  install -Dm755 "$S/zfsbootmenu/hooks/load-key.d/00-omarchy-netkey.sh" "$pkgdir/etc/zfsbootmenu/hooks/load-key.d/00-omarchy-netkey.sh"

  # --- vendored mkinitcpio hooks for the ZBM image -> /usr/share/omarchy-zfs ---
  # Staged here, not in /etc/zfsbootmenu/initcpio: generate-zbm only searches
  # directories listed in InitCPIOHookDirs, which omarchy-zfs-remote-unlock-setup
  # registers when it copies these into place. See vendor/README.md.
  install -Dm644 "$S/vendor/mkinitcpio-dropbear/dropbear_install" "$pkgdir/usr/share/omarchy-zfs/initcpio/install/dropbear"
  install -Dm755 "$S/vendor/mkinitcpio-dropbear/dropbear_hook"    "$pkgdir/usr/share/omarchy-zfs/initcpio/hooks/dropbear"
  install -Dm644 "$S/vendor/mkinitcpio-rclocal/rclocal_install"   "$pkgdir/usr/share/omarchy-zfs/initcpio/install/rclocal"
  install -Dm755 "$S/vendor/mkinitcpio-rclocal/rclocal_hook"      "$pkgdir/usr/share/omarchy-zfs/initcpio/hooks/rclocal"
  install -Dm644 "$S/vendor/mkinitcpio-dropbear/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE.mkinitcpio-dropbear"
  install -Dm644 "$S/vendor/mkinitcpio-rclocal/LICENSE"  "$pkgdir/usr/share/licenses/$pkgname/LICENSE.mkinitcpio-rclocal"

  # --- docs ---
  install -Dm644 "$S/docs/netkey-server.md" "$pkgdir/usr/share/doc/$pkgname/netkey-server.md"

  # --- default config -> /etc/omarchy-zfs ---
  install -Dm644 "$S/config/autosnap.conf" "$pkgdir/etc/omarchy-zfs/autosnap.conf"
  install -Dm644 "$S/config/bootorder.conf" "$pkgdir/etc/omarchy-zfs/bootorder.conf"

  # ZBM boots kernel+initramfs pairs from /boot; omarchy's limine flow only
  # builds a UKI on the ESP. This preset keeps the plain pair existing.
  install -Dm644 "$S/mkinitcpio/linux-zbm.preset" "$pkgdir/etc/mkinitcpio.d/linux-zbm.preset"

  install -Dm644 "$S/LICENSE" "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
